name: Post Tag

# This workflow contains our release automation.
on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  release-build:
    name: Release Build (macos-latest)
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: "/Applications/Xcode_26.0.app"
      SWIFT_VERSION: 6.2.3
    steps:
      - name: Select Xcode version
        run: |
          sudo xcode-select --switch "${DEVELOPER_DIR}/Contents/Developer"
          xcodebuild -version
      - name: Show Swift version
        run: swift --version
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Install jemalloc
        run: brew install jemalloc
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Build
        run: make build

  gh-release-notes:
    name: Release Notes
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Set TAG_NAME in Environment
        # Subsequent jobs will be have the computed tag name
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Create or Update Release
        env:
          # Required for the GitHub CLI
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./tools/build/github-release.sh --tag=${TAG_NAME}
